fix probe is nil
OT-CONTAINER-KIT/redis-operator pull request #323
Opened 2022-08-31 09:31 UTC by jiuker

when probe is nil,will panic.
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ccacb6]

goroutine 516 [running]:
redis-operator/k8sutils.getProbeInfo(0x0)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:349 +0x76
redis-operator/k8sutils.generateContainerDef({0xc000895af0, 0xc}, {{0xc000650a20, 0x1c}, {0xc000895b20, 0xc}, 0xc000a894a0, {0xc0000f4a80, 0x22}, {0x0, ...}, ...}, ...)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:226 +0xe5
redis-operator/k8sutils.generateStatefulSetsDef({{0xc000895af0, 0xc}, {0x0, 0x0}, {0xc000895b00, 0xd}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:134 +0x17e
redis-operator/k8sutils.CreateOrUpdateStateFul({_, _}, {{0xc000895af0, 0xc}, {0x0, 0x0}, {0xc000895b00, 0xd}, {0x0, 0x0}, ...}, ...)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:61 +0x1de
redis-operator/k8sutils.CreateStandaloneRedis(0xc00044cfc0)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/redis-standalone.go:40 +0x3fe
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc0003bf380, {0x2175208, 0xc0004e3f50}, {{{0xc000895b00, 0xd}, {0xc000895af0, 0xc}}})
        /home/jiuker/workspace/go/src/ot/redis-operator/controllers/redis_controller.go:63 +0x4ee
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00064c0b0, {0x2175208, 0xc0004e3f50}, {{{0xc000895b00, 0xd}, {0xc000895af0, 0xc}}})
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x365
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00064c0b0, {0x2175208, 0xc0004e3e90}, {0x1e6e540, 0xc00062a060})
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x425
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00064c0b0, {0x2175160, 0xc000c195c0})
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x398
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0xdc
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x4d6

```

2022-09-02 11:03 UTC, jiuker commented
@iamabhishek-dubey

2022-09-02 20:05 UTC, iamabhishek-dubey requested changes

2022-09-02 20:05 UTC, iamabhishek-dubey commented on k8sutils/statefulset.go
> +	// when probe is nil, return default handler
I believe we can define these default values using kubebuilders and crds.

https://book.kubebuilder.io/reference/markers/crd-validation.html

2022-09-02 20:05 UTC, iamabhishek-dubey commented
Also sign off your commit, please.
 https://github.com/OT-CONTAINER-KIT/redis-operator/pull/323/checks?check_run_id=8110611092

2022-09-03 02:57 UTC, jiuker commented
I apply this 
```yaml
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: test-redis
  name: test-redis
  namespace: mcamel-system
spec:
  kubernetesConfig:
    image: 'quay.io/opstree/redis:v6.2.5'
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: test-redis-secret
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  redisConfig:
    additionalRedisConfig: test-redis-conf-config
  redisExporter:
    enabled: true
    image: 'quay.io/opstree/redis-exporter:1.0'
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
```
And use master branch to build.
It will panic.
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ccacb6]

goroutine 516 [running]:
redis-operator/k8sutils.getProbeInfo(0x0)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:349 +0x76
redis-operator/k8sutils.generateContainerDef({0xc000895af0, 0xc}, {{0xc000650a20, 0x1c}, {0xc000895b20, 0xc}, 0xc000a894a0, {0xc0000f4a80, 0x22}, {0x0, ...}, ...}, ...)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:226 +0xe5
redis-operator/k8sutils.generateStatefulSetsDef({{0xc000895af0, 0xc}, {0x0, 0x0}, {0xc000895b00, 0xd}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:134 +0x17e
redis-operator/k8sutils.CreateOrUpdateStateFul({_, _}, {{0xc000895af0, 0xc}, {0x0, 0x0}, {0xc000895b00, 0xd}, {0x0, 0x0}, ...}, ...)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/statefulset.go:61 +0x1de
redis-operator/k8sutils.CreateStandaloneRedis(0xc00044cfc0)
        /home/jiuker/workspace/go/src/ot/redis-operator/k8sutils/redis-standalone.go:40 +0x3fe
redis-operator/controllers.(*RedisReconciler).Reconcile(0xc0003bf380, {0x2175208, 0xc0004e3f50}, {{{0xc000895b00, 0xd}, {0xc000895af0, 0xc}}})
        /home/jiuker/workspace/go/src/ot/redis-operator/controllers/redis_controller.go:63 +0x4ee
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00064c0b0, {0x2175208, 0xc0004e3f50}, {{{0xc000895b00, 0xd}, {0xc000895af0, 0xc}}})
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x365
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00064c0b0, {0x2175208, 0xc0004e3e90}, {0x1e6e540, 0xc00062a060})
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x425
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00064c0b0, {0x2175160, 0xc000c195c0})
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x398
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0xdc
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /home/jiuker/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x4d6
```
@iamabhishek-dubey

2022-09-19 09:09 UTC, closed without merging