addVolumeMount
OT-CONTAINER-KIT/redis-operator pull request #379
Opened 2022-11-17 15:05 UTC by shubham-cmyk

**Description**

Fixes #ISSUE

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Checklist**

- [ ] Testing has been performed
- [ ] No functionality is broken
- [ ] Documentation updated

2022-11-22 10:47 UTC, shubham-cmyk commented
Signed the Commit

2022-11-23 12:18 UTC, shubham-cmyk commented
I have tested the mouting 

![Screenshot from 2022-11-23 17-47-22](https://user-images.githubusercontent.com/69793468/203544976-3b680d2e-0553-4998-bc73-ce1ebbc6b8ad.png)

The container are mounted with the volume

2022-11-23 12:18 UTC, shubham-cmyk commented
@iamabhishek-dubey You can merge the PR

2022-11-24 04:58 UTC, iamabhishek-dubey requested changes

2022-11-24 04:58 UTC, iamabhishek-dubey commented on k8sutils/statefulset.go
> +	UserMountPath                []corev1.VolumeMount
Let's call it `AdditionalMountPath`

2022-11-24 04:59 UTC, iamabhishek-dubey commented
Also, it would be great if you can add an example for this in the [examples](https://github.com/OT-CONTAINER-KIT/redis-operator/tree/master/example) folder.

2022-11-28 13:07 UTC, iamabhishek-dubey commented on example/volume_Mount/redis-cluster.yaml
> +  # Tolerations: []
Can we remove other unnecessary maps and objects, just like in the other examples folder? Also, let's keep the name of folder in `snake_case`.

2022-11-28 13:08 UTC, iamabhishek-dubey commented on example/volume_Mount/redis-cluster.yaml
> +  # Tolerations: []
Also, add one example for standalone as well.

2022-11-29 08:13 UTC, closed without merging