Secrets gen by Operator
OT-CONTAINER-KIT/redis-operator pull request #391
Opened 2022-11-30 13:43 UTC by shubham-cmyk

fix #269 

Secrets now can be generate by the operator.

2022-12-05 17:03 UTC, iamabhishek-dubey commented on api/v1beta1/common_types.go
> +	ImagePullSecrets      *[]corev1.LocalObjectReference   `json:"imagePullSecrets,omitempty"`
```yaml
existingSecret:
   secretName: redis-secret
   key: password
autogeneratePassword:
   secretName: redis-secret
   namespaces: ["default", "test"]
```

2022-12-08 22:58 UTC, mxzinke commented on api/v1beta1/common_types.go
> +	ImagePullSecrets      *[]corev1.LocalObjectReference   `json:"imagePullSecrets,omitempty"`
I would prefer `autogeneratePasswordSecret`. And why generate the secret to multiple namespaces?

My suggestion:
```yaml
existingSecret:
  secretName: redis-secret
  key: password
  namespace: abc
autogeneratePasswordSecret:
  secretName: redis-secret
  key: password
  namespace: your-project-ns # Do we really need this? Or should it just be, where the rest is deployed?
```

2022-12-19 08:28 UTC, iamabhishek-dubey commented on api/v1beta1/common_types.go
> +	ImagePullSecrets      *[]corev1.LocalObjectReference   `json:"imagePullSecrets,omitempty"`
The purpose was to created this in different namespaces where application can consume this secret.

2023-01-07 17:11 UTC, iamabhishek-dubey requested changes

2023-01-07 17:11 UTC, iamabhishek-dubey commented on example/generated_secrets/redis-cluster.yaml
> +  name: shubham
Please correct the name of cluster and also I cannot see the new block in the example

2023-01-07 17:11 UTC, iamabhishek-dubey commented on k8sutils/secrets.go
> +
Owner ref is missing here

2023-08-10 15:43 UTC, darkrift commented
Any reason not to leverage https://redis.io/commands/acl-genpass/ ?

2023-08-10 15:50 UTC, shubham-cmyk commented
This could be used that's why this PR was on hold for so long

2023-08-10 16:19 UTC, shubham-cmyk commented
@darkrift I would like you to invite to slack channel : [Join our #redis-operator Slack Channel](https://opstree.slack.com/archives/C05MBRB50JG).

2025-01-11 02:36 UTC, closed without merging