Status for replication,sentinel,standalone
OT-CONTAINER-KIT/redis-operator pull request #639
Opened 2023-09-20 04:14 UTC by sadath-12

Fixes Issue : #638

2023-09-20 04:24 UTC, shubham-cmyk commented on config/crd/kustomization.yaml
Why you have deleted this file and other related files

2023-09-20 04:27 UTC, shubham-cmyk requested changes

2023-09-20 04:27 UTC, shubham-cmyk commented on config/crd/bases/redis.redis.opstreelabs.in_redisclusters.yaml
Discard this file. 
Open another PR for changes in the crd of the redis cluster 
since the change here you are pushing related to other feature.

2023-09-20 04:59 UTC, shubham-cmyk requested changes

2023-09-20 04:59 UTC, shubham-cmyk commented on api/status/redis-standalone_status.go
> +	BootstrapStandaloneReason    string = "RedisStandalone is bootstrapping"
This is never used

2023-09-20 05:13 UTC, sadath-12 commented on api/status/redis-standalone_status.go
> +	BootstrapStandaloneReason    string = "RedisStandalone is bootstrapping"
You mean the ```BootstrapStandaloneReason``` ?

2024-01-10 09:41 UTC, rashiga commented
hey, i am also looking for the same feature, when can this PR be merged? or if i can help with something - please do let me know!

2024-01-12 12:04 UTC, rashiga commented
Hey...
When can we expect these changes to be released..?

2024-04-02 00:31 UTC, wkd-woo commented
any update?

2025-05-04 13:02 UTC, closed without merging