[Feat] : support ignore specify annotation key in statefulset
OT-CONTAINER-KIT/redis-operator pull request #666
Opened 2023-10-09 13:24 UTC by drivebyer

**Description**

Fixes https://github.com/OT-CONTAINER-KIT/redis-operator/issues/555

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Checklist**

- [x] Tests have been added/modified and all tests pass.
- [ ] Functionality/bugs have been confirmed to be unchanged or fixed.
- [x] I have performed a self-review of my own code.
- [ ] Documentation has been updated or added where necessary.

**Additional Context**

2023-10-09 14:45 UTC, shubham-cmyk commented on api/common_types.go
> +	IgnoreAnnotations      []string                         `json:"ignoreAnnotations,omitempty"`
What if we want the map[String]String

2023-10-09 15:00 UTC, shubham-cmyk commented
We could have 

`tests/e2e/v1beta2/ignore-annots/redis-cluster`
& 
`tests/e2e/v1beta2/ignore-annots/redis-standalone`

2023-10-10 01:35 UTC, drivebyer commented
> @drivebyer Let's push another e2e to ensure the annotations are not present.
> If you need help on that ping me.

ok

2023-10-10 02:49 UTC, drivebyer commented
ready to review @shubham-cmyk

2023-10-10 04:43 UTC, shubham-cmyk commented on tests/_config/kuttl-test.yaml
> -- tests/e2e/v1beta2/setup
No need to remove this. 
The e2e test case would override this `testDirs` since we have passed that through CLI.

2023-10-10 04:45 UTC, shubham-cmyk commented on tests/e2e/v1beta2/ignore-annots/redis-cluster/cluster.yaml
> +        memory: 128Mi
```suggestion

```

Remove this we don't need a exporter here.

2023-10-10 04:49 UTC, shubham-cmyk commented
@drivebyer 

We need to have a file `annots-sts.yaml` in redis cluster and redis-standalone. 

Where we put that annots on the sts and put that file in the error or TestStep Like : 
Refer : https://kuttl.dev/docs/testing/reference.html#teststep

```
error:
- my-errored-new-resource.yaml
```

Error make sure that it would fail

2023-10-10 04:53 UTC, drivebyer commented
> Error make sure that it would fail

ok, i would add it

2023-10-10 04:55 UTC, shubham-cmyk commented
@drivebyer 
We should also add the 
[`ready-pvc.yaml`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/tests/e2e/v1beta2/setup/redis-cluster/ready-pvc.yaml)
& 
[`ready-cluster.yaml`](https://github.com/OT-CONTAINER-KIT/redis-operator/blob/master/tests/e2e/v1beta2/setup/redis-cluster/ready-cluster.yaml)

Make sure you have that annotation present in the `ready-cluster.yaml`. 


In standalone we do the same but we won't have the status there because currently it was not added to that.

2023-10-10 06:27 UTC, shubham-cmyk requested changes

2023-10-10 06:27 UTC, shubham-cmyk commented on tests/e2e/v1beta2/ignore-annots/redis-cluster/ignore-annots-sts.yaml
> +  name: redis-cluster-v1beta2-leader
Add this here also : need-ignore-key: "need-ignore-value"

2023-10-10 06:27 UTC, shubham-cmyk commented on tests/e2e/v1beta2/ignore-annots/redis-cluster/ignore-annots-sts.yaml
> +  name: redis-cluster-v1beta2-follower
add annots here also

2023-10-10 06:27 UTC, shubham-cmyk commented on tests/e2e/v1beta2/ignore-annots/redis-standalone/ignore-annots-sts.yaml
> +  name: redis-standalone-v1beta2
Add ignore annots here

2023-10-10 06:30 UTC, shubham-cmyk commented
It would be ready to merge after these changes.

2023-10-10 06:38 UTC, shubham-cmyk approved these changes
LGTM

2023-10-10 06:40 UTC, merged