Adding PodDisruptionBudget support
OT-CONTAINER-KIT/redis-operator pull request #90
Opened 2021-06-07 15:12 UTC by davidcollom

This adds support for Pod Disruption budgets to be managed by the controller so that labels always match and quorum is maintained within the redis cluster.

This includes both masters (leaders) and slaves (followers) for consistency but could be removed later (or have ability to increase slaves (followers) <> than masters (leaders) when in a read heavy environment.

2021-06-16 12:09 UTC, iamabhishek-dubey commented
Please fix merge conflict

2021-06-20 14:19 UTC, iamabhishek-dubey commented
Can you please fix the CI checks?

2021-06-21 08:59 UTC, davidcollom commented on controllers/rediscluster_controller.go
> +	return ctrl.Result{}, err
```suggestion
```

2021-06-24 17:28 UTC, iamabhishek-dubey commented
Looks fine, one small request please sign off the commit

2021-09-16 16:40 UTC, davidcollom commented
@iamabhishek-dubey PR Updated and merge conflicts resolved.

2021-11-23 16:22 UTC, davidcollom commented
@iamabhishek-dubey Any chance of getting this feature merged? 🙏

2021-12-26 13:29 UTC, iamabhishek-dubey commented
@davidcollom please fix the conflicts, I will merge this after it.

2021-12-31 13:59 UTC, davidcollom commented
@iamabhishek-dubey PR Updated and ready to review/merge

2022-01-01 17:31 UTC, iamabhishek-dubey requested changes

2022-01-01 17:31 UTC, iamabhishek-dubey commented on k8sutils/poddisruption.go
> +}
@davidcollom can we convert these two functions into a single one and pass the role to it as an argument. Because most things look the same to me.

2022-01-01 17:31 UTC, iamabhishek-dubey commented
@davidcollom a single comment, otherwise it looks good to merge

2022-01-04 18:38 UTC, davidcollom commented
@iamabhishek-dubey - All Feedback addressed and added an example for a redis-cluster.

2022-01-08 11:19 UTC, iamabhishek-dubey approved these changes

2022-01-08 11:19 UTC, merged

2022-01-19 17:48 UTC, amoon78 commented
Glad to see that this PR was merged to support PodDisruptionBudget but, I seems couldn't see any release related to this PR (https://github.com/OT-CONTAINER-KIT/redis-operator/releases) yet. 
Can I know when this change will be released? ty!